apiVersion: v1
kind: Namespace
metadata:
  name: smartgpt-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smartgpt-ui
  name: smartgpt-ui
  labels:
    app: smartgpt-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartgpt-ui
  template:
    metadata:
      labels:
        app: smartgpt-ui
    spec:
      containers:
        - name: smartgpt-ui
          image: <docker user>/smartgpt-ui:latest
          resources: {}
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  namespace: smartgpt-ui
  name: smartgpt-ui
  labels:
    app: smartgpt-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: smartgpt-ui
  type: ClusterIP
